```{r knitsetup, echo=FALSE, results='hide', warning=FALSE, message=FALSE, cache=FALSE}
opts_knit$set(base.dir='./', fig.path='', out.format='md')
opts_chunk$set(prompt=FALSE, comment='', results='markup')

library(ggvis)
library(knitr)
library(htmltools)
library(htmlwidgets)
library(pipeR)
```

<script src="../gitbook/plugins/gitbook-plugin-ggvis/lib/jquery/jquery.min.js"></script>
<link href="../gitbook/plugins/gitbook-plugin-ggvis/lib/jquery-ui/css/smoothness/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />
<script src="../gitbook/plugins/gitbook-plugin-ggvis/lib/jquery-ui/js/jquery-ui-1.10.4.custom.min.js"></script>
<script src="../gitbook/plugins/gitbook-plugin-ggvis/lib/d3/d3.min.js"></script>
<script src="../gitbook/plugins/gitbook-plugin-ggvis/lib/vega/vega.min.js"></script>
<script src="../gitbook/plugins/gitbook-plugin-ggvis/lib/lodash/lodash.min.js"></script>
<script>var lodash = _.noConflict();</script>
<link href="../gitbook/plugins/gitbook-plugin-ggvis/ggvis/css/ggvis.css" rel="stylesheet" />
<script src="../gitbook/plugins/gitbook-plugin-ggvis/ggvis/js/ggvis.js"></script>
<script src="../gitbook/plugins/gitbook-plugin-ggvis/ggvis/js/shiny-ggvis.js"></script>

# ggvis

ggvis


```{r eval = F}
mtcars %>>% ggvis(~mpg, ~wt)
```

```{r echo = F, message = F, results = 'asis'}
mtcars %>>% ggvis(~mpg, ~wt) %>>% knit_print -> text 
unclass(text)[1] %>>%
  ( gsub( x = ., pattern = "(<!--)([/]?html_preserve)[.]*-->", replacement = "")  ) %>>%
  HTML %>>% cat
  #print() %>>%
  #htmltools::html_print() %>>%
  #htmlwidgets:::pandoc_self_contained_html(output = "ggvis1.html") 

  #file.copy("tempggvis.html", "../_book/_fig/ggvis1.html")
```
